//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.DALL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImage
    {
        public int ImageId { get; set; }
        public string ResimTitle { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> ProductID { get; set; }
    }
}
